spring.application.name=Tabby

server.port=8080
spring.profiles.active=local

spring.datasource.url=jdbc:h2:file:./data/posdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=IngMapache
spring.datasource.password=2005

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.web.resources.static-locations=classpath:/static/
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
